#!/usr/bin/env bash
# ========================================================
# Credit Code By Project Rerechan
# Author: Rerechan02 (DindaPutriFN)
# License: This configuration is licensed for personal or internal use only.
# ========================================================

# Fungsi untuk mencetak pesan berwarna hijau
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

# Membaca domain dari file
domain=$(cat /usr/local/etc/v2ray/domain)

# Membaca input JSON dari API
input_data=$(cat)

# Ekstrak data dari JSON
user=$(echo "$input_data" | jq -r '.user')
masaaktif=$(echo "$input_data" | jq -r '.masaaktif')

# Validasi jika user sudah ada
CLIENT_EXISTS=$(grep -w $user /usr/local/etc/v2ray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
    echo -e "{\"status\": \"false\", \"message\": \"User already exists, please choose another name.\"}"
    exit 1
fi

# Generate UUID baru
uuid=$(cat /proc/sys/kernel/random/uuid)

# Hitung tanggal kedaluwarsa
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")

# Menambahkan user baru ke config.json
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /usr/local/etc/v2ray/config.json

# Restart V2Ray
systemctl restart v2ray

# Membuat link VLESS TLS, NTLS, dan GRPC
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"

# Response data dalam format JSON
response=$(cat <<EOF
{
    "status": "true",
    "code": 200,
    "message": "Akun VLESS berhasil dibuat",
    "user": "$user",
    "domain": "$domain",
    "uuid": "$uuid",
    "tls_port": "443",
    "ntls_ports": "80, 2082",
    "path": "/vless",
    "service_name": "vless-grpc",
    "links": {
        "tls": "$vlesslink1",
        "ntls": "$vlesslink2",
        "grpc": "$vlesslink3"
    },
    "expiration_date": "$exp"
}
EOF
)

# Outputkan respons dalam format JSON
clear
echo -e "$response"