#!/usr/bin/env bash
# ========================================================
# Credit Code By Project Rerechan
# Author: Rerechan02 (DindaPutriFN)
# License: This configuration is licensed for personal or internal use only.
#          Redistribution, resale, or reuse of this code in any form
#          without explicit written permission from the author is prohibited.
#          Selling this code or its derivatives is strictly forbidden.
# ========================================================

red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/usr/local/etc/v2ray/config.json")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo -e "───────────────────────────"
    echo -e "    RENEW VMESS ACCOUNT    "
    echo -e "───────────────────────────"
    echo ""
    echo "You have no existing clients!"
    echo ""
    echo -e "───────────────────────────"
    echo ""
    read -n 1 -s -r -p "Press any key to back on menu"
    menu
fi

clear
echo -e "───────────────────────────"
echo -e "    RENEW VMESS ACCOUNT    "
echo -e "───────────────────────────"
echo ""
grep -E "^### " "/usr/local/etc/v2ray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
echo ""
red "tap enter to go back"
echo -e "───────────────────────────"
read -rp "Input Username : " user
if [ -z $user ]; then
    menu
else
    read -p "Expired (days): " masaaktif
    exp=$(grep -wE "^### $user" "/usr/local/etc/v2ray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    exp3=$(($exp2 + $masaaktif))
    exp4=$(date -d "$exp3 days" +"%Y-%m-%d")
    sed -i "/### $user/c\### $user $exp4" /usr/local/etc/v2ray/config.json
    systemctl restart v2ray >/dev/null 2>&1
    clear
    echo -e "───────────────────────────"
    echo -e "RENEW ACCOUNT SUCCESSFULLY "
    echo -e "───────────────────────────"
    echo ""
    echo " Client Name : $user"
    echo " Expired On  : $exp4"
    echo ""
    echo -e "───────────────────────────"
    echo ""
fi